# Generated by Django 5.2.6 on 2025-09-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название модели автомобиля', max_length=100, verbose_name='Автомобиль')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год начала выпуска')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Оставьте поле пустым, если автомобиль еще выпускается', null=True, verbose_name='Год окончания выпуска')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название страны', max_length=30, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment_text', models.TextField(help_text='Максимальная длина коммента - 1000 символов', max_length=1000, verbose_name='Текст комментария')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название производителя', max_length=150, verbose_name='Название производителя')),
                ('country', models.ForeignKey(help_text='Выберите страну производителя', on_delete=django.db.models.deletion.CASCADE, related_name='manufactures', to='reviews.country')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='manufacture',
            field=models.ForeignKey(help_text='Выберите производителя', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='reviews.manufacture'),
        ),
    ]
