# Generated by Django 5.2.6 on 2025-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(help_text='Введите название модели автомобиля', max_length=100, unique=True, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Введите название страны', max_length=30, unique=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(help_text='Введите название производителя', max_length=150, unique=True, verbose_name='Название производителя'),
        ),
    ]
